### ISSUE TITLE
No atlas solution found?

### ISSUE THREAD

**Issue by Magicrafter13** [devkitPro/tex3ds#17]
Today I added 2 new sprites, so I opened the sprites.t3s file and added the two file names to my large list of sprites.
I went to compile and it said 'No atlas solution found.'
If I remove the 2 lines (the 2 filenames) from the file again, it compiles fine.
Is there a sprite limit or something?

**Comment by mtheall** [comment]
All your sprites must fit into a single 1024x1024 texture. "No atlas solution found" means it couldn't tile them all within these bounds. There's a possibility that such a solution exists, but we just couldn't find one.

**Comment by Magicrafter13** [comment]
Can I incorporate multiple t3s files in one project? (Thus splitting up the sprites into groups instead of all game sprites in one file)

**Comment by mtheall** [comment]
Yes. Each .t3s would output a .t3x.

**Comment by Magicrafter13** [comment]
Thank you

**Comment by Magicrafter13** [comment]
okay, so the sprite on the first line of file1.t3s and the sprite on the first line of file2.t3s are both the same id. How do I tell the drawing function to draw the proper sprite? I'll explain this a bit better, so in the sprites.t3s file on the third line I have game\crawl_4.png and in the ui.t3s file on the third line I have title.png
to make sprites easier to draw for me, I do assign each id to a variable, but basically in my code I have this:
size_t titleID = ui_title_idx;
and I give titleID to the draw function
but instead of drawing the title screen image, it's drawing the crawl_4.png
So based on that, I assumed that they must be using the same ID.

So how do I differentiate these sprites in my code?

**Comment by Magicrafter13** [comment]
oh nevermind, I'm an idiot.
so I have a function called draw_texture, all I do is provide it with an ID, an x, and a y value. I forgot about the whole C2D_SpriteSheet thing.

Jesus...
