### ISSUE TITLE
Wrong output for l4(a4) pixel format

### ISSUE THREAD

**Issue by LITTOMA** [devkitPro/tex3ds#29]
Input: [font.png](https://github.com/LITTOMA/bugreports/blob/main/tex3ds-font.png)
Output: [font.tex](https://github.com/LITTOMA/bugreports/blob/main/tex3ds-font.png)
Command: `tex3ds --raw -z none -f l4 -o font.tex font.png`
Running on: Windows 10 x64, msys2
Version: tex3ds v1.0.1

The input file is a 512*512 image, so ouput must be 128KB in 4bpp formats.
However, tex3ds outputs a 256 KB file.

**Comment by mtheall** [comment]
Can you give more specific info? Maybe some input/output files and screenshots running on hardware.

**Comment by LITTOMA** [comment]
> Can you give more specific info? Maybe some input/output files and screenshots running on hardware.

Sure, updated description.

**Comment by mtheall** [comment]
https://github.com/devkitPro/tex3ds/blob/8c34b1ef90d4700fa0f094180bc88c07c5b62eef/source/encode.cpp#L426
https://github.com/devkitPro/tex3ds/blob/8c34b1ef90d4700fa0f094180bc88c07c5b62eef/source/encode.cpp#L466
Seems like these should be `i += 2`

**Comment by mtheall** [comment]
Can you verify if this fixes the issue?

**Comment by LITTOMA** [comment]
Yes, it works properly now! Thank you.
